<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }

            thead {
                background-color: #274982;
                color: #fff;
            }

            tbody {
                text-align: left;
            }

            table {
                max-width: 600px;
                margin-left: 200px;
            }

        </style>
    </head>
    <body>
        <h1>Slim</h1>
        <div>a microframework for PHP</div>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a></p>
        <?php endif; ?>
        
        <table>
            <thead>
                <tr>
                    <td>ID</td>
                    <td>Name</td>
                    <td>Description</td>
                </tr>
            </thead>
            <tbody> 
                <?php foreach ($result as $row) : ?>
                    <tr>
                        <td><?= $row['CategoryID'] ?></td>
                        <td><?= $row['CategoryName'] ?></td>
                        <td><?= $row['CategoryDescription'] ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </ul>
        </table>
    </body>
</html>
